export enum CreateDaoDialogId {
    PUBLISH_DAO = 'PUBLISH_DAO',
    CREATE_DAO_DETAILS = 'CREATE_DAO_DETAILS',
    CREATE_PROCESS_DETAILS = 'CREATE_PROCESS_DETAILS',
    CREATE_DRAW_DETAILS = 'CREATE_DRAW_DETAILS',
    PREPARE_PROCESS = 'PREPARE_PROCESS',
    SETUP_BODY = 'SETUP_BODY',
    SETUP_STAGE_SETTINGS = 'SETUP_STAGE_SETTINGS',
    PREPARE_DRAW = 'PREPARE_DRAW',
    SETUP_APPS_BODY = 'SETUP_APPS_BODY',
}
